### PR TITLE
Changing tile parser algorithm so that it can detect rows listed in either row-by-row or snake by row collection type.

### PR DESCRIPTION
**Pull request by joeykleingers**
Changing tile parser algorithm so that it can detect rows regardless of if the tiles are listed row-by-row or snake by rows.  Also detects rows even if the tiles are listed from bottom-left to top-right or bottom-right to top-left.

### CODE REVIEW

**Comment by joeykleingers** [comment]
Changed the title again to better reflect what was implemented.

**Comment by thewtex** [comment]
Should this be rebased on `master` or abandoned?

**Comment by joeykleingers** [comment]
This PR basically just changes the tile parser algorithm so that it can detect rows when they are snaking instead of row-by-row.  Right now the parser assumes row-by-row.  We may want to expand this in the future so that it can handle row detection regardless of what order the tiles are in.

**Comment by dzenanz** [comment]
This will probably need to be rebased on master to have the tests pass.

**Comment by dzenanz** [comment]
I rebased this on top of current master.

**Comment by dzenanz** [comment]
This causes the registered configuration to be interpreted all as one row (9x1 montage):
```text
# Define the number of dimensions we are working on
dim = 2

# Define the image coordinates
100.tif; ; (0.0, 0.0)
101.tif; ; (1123.9349, -4.6711893)
102.tif; ; (2247.1252, -9.281502)
105.tif; ; (4.2074594, 846.7166)
104.tif; ; (1127.7086, 841.58563)
103.tif; ; (2251.1025, 836.9782)
106.tif; ; (8.303699, 1689.2762)
107.tif; ; (1131.778, 1684.0345)
108.tif; ; (2255.0415, 1679.3828)
```
instead of a square 3x3 montage. That's what is causing the crashes in OMC tests.

**Comment by joeykleingers** [comment]
You rebased it into master.. so we need to reverse those changes, right?

**Comment by dzenanz** [comment]
Master had only unrelated changes. And I think it was also crashing originally, before rebasing.

**Pull request closed without merging**
