### PR TITLE
ENH: Require less components to be built for examples

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Review by tbirdso — COMMENTED** [review]
@dzenanz Code looks good. Am I correct in understanding that `ITKTestKernel` is the only component that is no longer required to build for running ITKMontage examples here? If so, could that detail please be added to the commit message?

**Comment by dzenanz** [comment]
ITKTestKernel brings in a lot of IOs. If you think it is worthwhile, I could still update the commit message.

**Comment by tbirdso** [comment]
Updating the commit message would help if someone has to look back through history, thanks. If tests are passing then it could be updated and merged without waiting for tests to re-run.

**Comment by dzenanz** [comment]
Tests were passing, though I am not sure how sensitive they are to this change. I updated the commit message and merged.

**Pull request merged**
