### PR TITLE
BUG: fix huge errors in Tiles test

### PR DESCRIPTION
**Pull request by dzenanz**
introduce smaller but significant errors in 3D synthetic tests

### CODE REVIEW

**Comment by dzenanz** [comment]
What should we do about this wrap-around-the-middle artifact? Evaluate some normal image similarity metric at both positions and see which one better? And only do this close to the middle e.g. [25%, 75%] of image size? Something else entirely?

**Comment by thewtex** [comment]
Is this occurring in the padded region? Can we exclude or crop the padded region?

**Comment by dzenanz** [comment]
This is occurring around the middle of the image.

**Comment by thewtex** [comment]
Let's discuss more tomorrow.

**Comment by dzenanz** [comment]
Picking `index[i] - size[i]` or just `index[i]` can be done so it minimizes the translation (once origins are accounted for). This would avoid expensive computations, and only requires passing input images to the optimizer.

**Pull request closed without merging**
