### PR TITLE
Reducing limitations

### PR DESCRIPTION
**Pull request by dzenanz**
When comparing with Fiji result, test 10-129-C_2 accumulates around 10 pixels of shift over the montage. But it looks very close to it, even at the bottom.

The last tile in a row doesn't get a correct registration, possibly due to some blur along the overlapping edge.

### CODE REVIEW

**Comment by imikejackson** [comment]
Please add a readme to the S200 and 10-129-C (HiPercomp) data sets stating that there were publicly released by U.S. Air Force Public Affairs office under PA number:
88ABW-2103-0127

**Comment by dzenanz** [comment]
@imikejackson are MNML 3 and 5 also released? If yes, is it the same PA number?

**Comment by thewtex** [comment]
Will add PA numbers in another PR.

**Comment by thewtex** [comment]
Release numbers added in #93

**Pull request merged**
